import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const projectRoot = process.cwd();

test("container runtime files exist with the expected base configuration", () => {
	const dockerfilePath = join(projectRoot, "Dockerfile");
	const composePath = join(projectRoot, "docker-compose.yml");
	const prodComposePath = join(projectRoot, "docker-compose.prod.yml");
	const dockerignorePath = join(projectRoot, ".dockerignore");
	const envExamplePath = join(projectRoot, ".env.example");
	const nginxConfigPath = join(projectRoot, "deploy", "nginx", "default.conf");
	const packageJsonPath = join(projectRoot, "package.json");
	const sidecarChromeScriptPath = join(projectRoot, "scripts", "sidecar-chrome.mjs");

	assert.equal(existsSync(dockerfilePath), true);
	assert.equal(existsSync(composePath), true);
	assert.equal(existsSync(prodComposePath), true);
	assert.equal(existsSync(dockerignorePath), true);
	assert.equal(existsSync(envExamplePath), true);
	assert.equal(existsSync(nginxConfigPath), true);
	assert.equal(existsSync(sidecarChromeScriptPath), true);

	const dockerfile = readFileSync(dockerfilePath, "utf8");
	assert.match(dockerfile, /FROM node:22-bookworm-slim/i);
	assert.match(dockerfile, /apt-get install -y --no-install-recommends git curl ca-certificates/i);
	assert.match(dockerfile, /ENV HOST=0\.0\.0\.0/);
	assert.match(dockerfile, /ENV PORT=3000/);
	assert.match(dockerfile, /HEALTHCHECK/i);
	assert.match(dockerfile, /EXPOSE 3000/);
	assert.match(dockerfile, /CMD \["npm", "start"\]/);

	const compose = readFileSync(composePath, "utf8");
	assert.match(compose, /services:/);
	assert.match(compose, /ugk-pi:/);
	assert.match(compose, /ugk-pi-browser:/);
	assert.match(compose, /ugk-pi-browser-cdp:/);
	assert.match(compose, /3000:3000/);
	assert.match(compose, /127\.0\.0\.1:\$\{WEB_ACCESS_BROWSER_GUI_PORT:-3901\}:3001/);
	assert.match(compose, /HOST:\s*0\.0\.0\.0/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PROVIDER:\s*direct_cdp/);
	assert.match(compose, /WEB_ACCESS_CDP_HOST:\s*172\.31\.250\.10/);
	assert.match(compose, /WEB_ACCESS_CDP_PORT:\s*9223/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL:\s*http:\/\/ugk-pi:3000/);
	assert.match(compose, /lscr\.io\/linuxserver\/chrome:latest/);
	assert.match(compose, /alpine\/socat:latest/);
	assert.match(compose, /network_mode:\s*"service:ugk-pi-browser"/);
	assert.match(compose, /ipv4_address:\s*172\.31\.250\.10/);
	assert.match(compose, /subnet:\s*172\.31\.250\.0\/24/);
	assert.match(compose, /CHROME_CLI:\s*"--remote-debugging-address=0\.0\.0\.0 --remote-debugging-port=9222/);
	assert.match(compose, /CHROME_CLI:.*--hide-crash-restore-bubble/);
	assert.match(compose, /CHROME_CLI:.*--ozone-platform=x11/);
	assert.doesNotMatch(compose, /--ozone-platform=wayland/);
	assert.match(compose, /SELKIES_USE_BROWSER_CURSORS:\s*"true"/);
	assert.match(compose, /DISPLAY:\s*":0"/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PROFILE_DIR:-\/config\/chrome-profile-sidecar/);
	assert.match(compose, /TCP-LISTEN:9223,fork,bind=0\.0\.0\.0,reuseaddr/);
	assert.match(compose, /npm run dev/);

	const prodCompose = readFileSync(prodComposePath, "utf8");
	assert.match(prodCompose, /services:/);
	assert.match(prodCompose, /ugk-pi:/);
	assert.match(prodCompose, /ugk-pi-browser:/);
	assert.match(prodCompose, /ugk-pi-browser-cdp:/);
	assert.match(prodCompose, /nginx:/);
	assert.match(prodCompose, /restart:\s*unless-stopped/);
	assert.match(prodCompose, /env_file:/);
	assert.match(prodCompose, /\.env/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PROVIDER:\s*direct_cdp/);
	assert.match(prodCompose, /WEB_ACCESS_CDP_HOST:\s*172\.31\.250\.10/);
	assert.match(prodCompose, /WEB_ACCESS_CDP_PORT:\s*9223/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL:\s*http:\/\/ugk-pi:3000/);
	assert.match(prodCompose, /127\.0\.0\.1:\$\{WEB_ACCESS_BROWSER_GUI_PORT:-3901\}:3001/);
	assert.match(prodCompose, /lscr\.io\/linuxserver\/chrome:latest/);
	assert.match(prodCompose, /alpine\/socat:latest/);
	assert.match(prodCompose, /network_mode:\s*"service:ugk-pi-browser"/);
	assert.match(prodCompose, /ipv4_address:\s*172\.31\.250\.10/);
	assert.match(prodCompose, /subnet:\s*172\.31\.250\.0\/24/);
	assert.match(prodCompose, /CHROME_CLI:\s*"--remote-debugging-address=0\.0\.0\.0 --remote-debugging-port=9222/);
	assert.match(prodCompose, /CHROME_CLI:.*--hide-crash-restore-bubble/);
	assert.match(prodCompose, /CHROME_CLI:.*--ozone-platform=x11/);
	assert.doesNotMatch(prodCompose, /--ozone-platform=wayland/);
	assert.match(prodCompose, /SELKIES_USE_BROWSER_CURSORS:\s*"true"/);
	assert.match(prodCompose, /DISPLAY:\s*":0"/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PROFILE_DIR:-\/config\/chrome-profile-sidecar/);
	assert.match(prodCompose, /TCP-LISTEN:9223,fork,bind=0\.0\.0\.0,reuseaddr/);
	assert.match(prodCompose, /npm start/);
	assert.match(prodCompose, /healthcheck:/);
	assert.match(prodCompose, /logs\/app/);
	assert.match(prodCompose, /logs\/nginx/);
	assert.match(prodCompose, /runtime\/skills-user/);
	assert.match(prodCompose, /default\.conf/);
	assert.match(prodCompose, /depends_on:/);

	const envExample = readFileSync(envExamplePath, "utf8");
	assert.match(envExample, /DASHSCOPE_CODING_API_KEY=/);
	assert.match(envExample, /HOST=0\.0\.0\.0/);
	assert.match(envExample, /PORT=3000/);
	assert.match(envExample, /HOST_PORT=3000/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_GUI_PORT=3901/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_PROFILE_DIR=\/config\/chrome-profile-sidecar/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL=http:\/\/ugk-pi:3000/);

	const dockerignore = readFileSync(dockerignorePath, "utf8");
	assert.match(dockerignore, /node_modules/);
	assert.match(dockerignore, /\.git/);
	assert.match(dockerignore, /\.data/);

	const nginxConfig = readFileSync(nginxConfigPath, "utf8");
	assert.match(nginxConfig, /proxy_pass http:\/\/ugk-pi:3000/);
	assert.match(nginxConfig, /location \/healthz/);

	const packageJson = readFileSync(packageJsonPath, "utf8");
	assert.match(packageJson, /docker:logs:prod/);
	assert.match(packageJson, /docker:logs:nginx/);
	assert.match(packageJson, /docker:status:prod/);
	assert.match(packageJson, /docker:health:prod/);
	assert.match(packageJson, /docker:chrome:start/);
	assert.match(packageJson, /docker:chrome:restart/);
	assert.match(packageJson, /docker:chrome:check/);
	assert.match(packageJson, /docker:chrome:status/);
	assert.match(packageJson, /docker:chrome:open/);

	const sidecarChromeScript = readFileSync(sidecarChromeScriptPath, "utf8");
	assert.match(sidecarChromeScript, /hide-crash-restore-bubble/);
	assert.match(sidecarChromeScript, /--ozone-platform=x11/);
	assert.match(sidecarChromeScript, /export DISPLAY=:0/);
	assert.doesNotMatch(sidecarChromeScript, /--ozone-platform=wayland/);
	assert.doesNotMatch(sidecarChromeScript, /WAYLAND_DISPLAY=wayland-1/);
	assert.match(sidecarChromeScript, /exited_cleanly/);
	assert.match(sidecarChromeScript, /exit_type/);
	assert.match(sidecarChromeScript, /"check"/);
	assert.match(sidecarChromeScript, /"status"/);
	assert.match(sidecarChromeScript, /"open"/);
	assert.match(sidecarChromeScript, /check-deps\.mjs/);
	assert.match(sidecarChromeScript, /json\/version/);
});
