import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("server ops script protects shared runtime state during deploys", () => {
	const script = readFileSync("scripts/server-ops.mjs", "utf8");

	assert.match(script, /tencent/);
	assert.match(script, /aliyun/);
	assert.match(script, /deployRemote: "origin"/);
	assert.match(script, /deployRemote: "gitee"/);
	assert.match(script, /git fetch \$\{target\.deployRemote\} main/);
	assert.match(script, /git pull --ff-only \$\{target\.deployRemote\} main/);
	assert.match(script, /shellQuote/);
	assert.match(script, /replaceAll\("'", "'\\\\''"\)/);
	assert.match(script, /sh -lc \$\{shellQuote\(command\)\}/);
	assert.match(script, /< \/dev\/null/);
	assert.match(script, /UGK_RUNTIME_SKILLS_USER_DIR/);
	assert.match(script, /UGK_AGENT_DATA_DIR/);
	assert.match(script, /\/home\/ubuntu\/ugk-claw-shared\/runtime\/skills-user/);
	assert.match(script, /\/root\/ugk-claw-shared\/runtime\/skills-user/);
	assert.match(script, /\/home\/ubuntu\/ugk-claw-shared\/\.data\/agent/);
	assert.match(script, /\/root\/ugk-claw-shared\/\.data\/agent/);
	assert.match(script, /git status --short/);
	assert.match(script, /Remote worktree is dirty; stop before deploying/);
	assert.match(script, /docker compose --env-file/);
	assert.match(script, /config --quiet/);
	assert.match(script, /up --build -d/);
	assert.match(script, /restart nginx/);
	assert.match(script, /WEB_ACCESS_BROWSER_PROVIDER[\s\S]*direct_cdp/);
	assert.match(script, /UGK_AGENTS_DATA_DIR/);
	assert.match(script, /\/app\/\.data\/agents/);
	assert.match(script, /browser memory limit/);
	assert.match(script, /HostConfig\.Memory/);
	assert.match(script, /Chrome V8 old space limit/);
	assert.match(script, /max-old-space-size=1536/);
	assert.match(script, /127\.0\.0\.1:9222\/json\/version/);
	assert.match(script, /172\.31\.250\.10:9223\/json\/version/);
	assert.match(script, /\/app\/\.data\/agent/);
	assert.match(script, /preserve model settings/);
	assert.match(script, /model-settings\.json/);
	assert.match(script, /docker cp "\$APP_CID":\/app\/\.pi\/settings\.json/);
	assert.match(script, /\/v1\/debug\/skills/);
	assert.match(script, /\/v1\/debug\/runtime/);
	assert.match(script, /runtime debug/);
	assert.match(script, /failed=/);
	assert.match(script, /sys\.exit\(1 if failed or not data\.get/);
});
