services:
  ugk-pi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
